package com.dsrc.transport

import java.io.File
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertFailsWith
import kotlin.test.assertTrue

/**
 * Compared against CPython itself, not against a transcription.
 *
 * `python_double_repr.json` pairs raw IEEE-754 bit patterns with the exact text
 * `json.dumps` emits, generated by running it. Transcribing expected strings by hand
 * would risk agreeing with the bug, and the golden frame vectors cannot help here at
 * all: every float in them lies in the range where Kotlin and Python already agree.
 */
class DoublesTest {

    private data class Case(val bits: Long, val expected: String)

    private val cases: List<Case> by lazy {
        val text = javaClass.getResourceAsStream("/python_double_repr.json")
            ?.bufferedReader()?.readText()
            ?: error("python_double_repr.json is missing from the test resources")
        // Parsed by hand: the module under construction is the JSON codec, so a test
        // for it cannot depend on one.
        Regex("""\{\s*"bits":\s*(-?\d+),\s*"json":\s*"([^"]*)"\s*}""")
            .findAll(text)
            .map { Case(it.groupValues[1].toLong(), it.groupValues[2]) }
            .toList()
    }

    @Test
    fun `the reference table is present and substantial`() {
        // Guards the whole class: a missing or truncated resource would make every
        // assertion below pass over an empty list.
        assertTrue(cases.size > 1_000, "only ${cases.size} reference cases")
    }

    @Test
    fun `every reference case formats exactly as python does`() {
        val failures = mutableListOf<String>()
        for (case in cases) {
            val value = Double.fromBits(case.bits)
            val actual = Doubles.format(value)
            if (actual != case.expected) {
                failures.add("bits=${case.bits} expected=${case.expected} actual=$actual")
            }
        }
        assertTrue(
            failures.isEmpty(),
            "diverged from python on ${failures.size} of ${cases.size} cases:\n" +
                failures.take(20).joinToString("\n"),
        )
    }

    @Test
    fun `every formatted value round-trips back to the same double`() {
        // Shortest-round-trip is the other half of the contract: the text has to parse
        // back to the identical bit pattern, or the peer reconstructs a different number.
        for (case in cases) {
            val value = Double.fromBits(case.bits)
            val text = Doubles.format(value)
            assertEquals(
                value.toRawBits(),
                text.toDouble().toRawBits(),
                "round trip of $text",
            )
        }
    }

    @Test
    fun `the four layout boundaries are where python puts them`() {
        // 1e-4 is fixed and 1e-5 is scientific; 1e15 is fixed and 1e16 is scientific.
        // These are the cases Kotlin's own toString gets wrong in both directions.
        assertEquals("0.0001", Doubles.format(1e-4))
        assertEquals("1e-05", Doubles.format(1e-5))
        assertEquals("1000000000000000.0", Doubles.format(1e15))
        assertEquals("1e+16", Doubles.format(1e16))
    }

    @Test
    fun `values kotlin spells with an exponent and python does not`() {
        assertEquals("10000000.0", Doubles.format(1e7))
        assertEquals("12345678.0", Doubles.format(12345678.0))
        assertEquals("0.001", Doubles.format(1e-3))
    }

    @Test
    fun `a near-zero gyro reading is spelled python's way`() {
        // The value that would have shipped wrong: Kotlin says 1.5E-5.
        assertEquals("1.5e-05", Doubles.format(1.5e-5))
        assertEquals("-1.5e-05", Doubles.format(-1.5e-5))
    }

    @Test
    fun `the exponent always carries a sign and two digits`() {
        assertEquals("1e-05", Doubles.format(1e-5))
        assertEquals("1e+16", Doubles.format(1e16))
        assertEquals("1e-100", Doubles.format(1e-100))
        assertEquals("1e+100", Doubles.format(1e100))
    }

    @Test
    fun `an integral value keeps its trailing point-zero`() {
        assertEquals("35.0", Doubles.format(35.0))
        assertEquals("1.0", Doubles.format(1.0))
        assertEquals("1000.0", Doubles.format(1000.0))
        assertEquals("50.0", Doubles.format(50.0))
    }

    @Test
    fun `negative zero keeps its sign`() {
        assertEquals("-0.0", Doubles.format(-0.0))
        assertEquals("0.0", Doubles.format(0.0))
    }

    @Test
    fun `the extremes of the range are handled`() {
        assertEquals("5e-324", Doubles.format(Double.MIN_VALUE))
        assertEquals("1.7976931348623157e+308", Doubles.format(Double.MAX_VALUE))
        assertEquals("-1.7976931348623157e+308", Doubles.format(-Double.MAX_VALUE))
    }

    @Test
    fun `every float in the golden frame vectors is spelled correctly`() {
        // These pass under Kotlin's own toString too, which is exactly why they are not
        // sufficient on their own -- but they still have to hold.
        val fromVectors = mapOf(
            -0.2 to "-0.2", -0.1278 to "-0.1278", -0.02 to "-0.02", 0.0 to "0.0",
            0.01 to "0.01", 0.1 to "0.1", 0.42 to "0.42", 0.5 to "0.5", 0.87 to "0.87",
            0.9 to "0.9", 1.5 to "1.5", 1.6 to "1.6", 5.0 to "5.0", 9.79 to "9.79",
            9.9 to "9.9", 11.176 to "11.176", 13.4 to "13.4", 25.0 to "25.0",
            27.5 to "27.5", 35.0 to "35.0", 49.8 to "49.8", 50.0 to "50.0",
            51.5 to "51.5", 51.5074 to "51.5074", 91.2 to "91.2", 1500.0 to "1500.0",
        )
        for ((value, expected) in fromVectors) {
            assertEquals(expected, Doubles.format(value))
        }
    }

    @Test
    fun `a non-finite value is refused rather than written`() {
        // Python writes a bare NaN token that a strict parser rejects, so an encoder
        // must map non-finite values to null before framing rather than emit them.
        assertFailsWith<IllegalArgumentException> { Doubles.format(Double.NaN) }
        assertFailsWith<IllegalArgumentException> { Doubles.format(Double.POSITIVE_INFINITY) }
        assertFailsWith<IllegalArgumentException> { Doubles.format(Double.NEGATIVE_INFINITY) }
    }
}
