#!/usr/bin/env python3
"""Build the SUMO Mainz scenario from the SRC paper's Vissim network.

    .venv/bin/python scripts/build_mainz_scenario.py

Reads `data/mainz/Mainz20base.inpx` and `data/mainz/rl_links_mainz.txt` and writes
`mainz.net.xml`, `mainz.rou.xml` and `mainz_segments.json` beside them.

Three things about the conversion are decisions rather than mechanics, and each is
visible in the output so it can be checked:

**Speed.** Every edge imports at 13.9 m/s (50 km/h), and the SRC action set tops out
at 60 km/h. In Vissim a desired speed may exceed the link's nominal speed; in SUMO
`setSpeed` is capped by `getAllowedSpeed`, so the top action would silently clamp and
become indistinguishable from releasing the vehicle. `--speed.factor 1.2` lifts the
network to 16.67 m/s so all three actions are expressible, and makes the released
state equal to the fastest action exactly as `def_speed = speeds[-1]` does in SRC.

**Split links.** A Vissim link with a connector attaching part-way along becomes two
SUMO edges, `N[0]` and `N[1]`. Link 206 is the only one here, and it lies on every
route, so a name-for-name mapping loses all eight of them. Link ids are expanded to
their SUMO parts everywhere.

**Dropped links.** netconvert refuses links 24 and 68. Both sit in super-segment 8 and
neither appears on any demand route, so they are dropped from that segment's
membership rather than silently counted as present.
"""
from __future__ import annotations

import argparse
import json
import math
import re
import subprocess
import sys
import xml.etree.ElementTree as ET
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
DATA = REPO_ROOT / "data" / "mainz"

# 50 km/h * 1.2 = 60 km/h, the fastest action in the SRC action set.
SPEED_FACTOR = 1.2
# Vissim numbers connectors from 10000 up in this file; they become SUMO's internal
# edges and never appear as named ones.
CONNECTOR_ID_BASE = 10000


def drop_build_time(net: Path) -> None:
    """Remove netconvert's build timestamp from the net it just wrote.

    The network is committed, so that a diff answers "did the scenario change?". A
    timestamp in the header makes every rebuild a diff and the question unanswerable.
    Everything else netconvert writes is deterministic, including the version and the
    full configuration it was invoked with, and those are the provenance worth keeping.
    """
    lines = net.read_text().splitlines(keepends=True)
    for index, line in enumerate(lines):
        if line.startswith("<!-- generated on "):
            _, _, tail = line.partition(" by ")
            lines[index] = f"<!-- generated by {tail}"
            break
    net.write_text("".join(lines))


def add_exit_constraint(net: Path, speed_mps: float, green_fraction: float,
                        cycle_s: float, lanes: int = 0) -> float:
    """Continue the network past its exit into a road whose discharge we set.

    Vehicles reaching the end of a route leave instantly, so whatever edge they leave
    from sets the outflow cap. Here that is link 218, three lanes at 60 km/h, which
    caps outflow at 3,899 veh/h -- above the 2,880 the network delivers, so it never
    binds and the exit behaves as a sink that absorbs everything offered. A road does
    not do that: it continues into another road that can carry a finite flow.

    The SRC paper describes a backpressure element at the exit, but no published
    layout contains one -- the conflict area on link 218 is PASSIVE in the base and
    absent from all four signalised variants -- so this is a stated modelling choice of
    ours rather than a reproduction of theirs.

    THE CONSTRAINT IS THE SIGNAL, NOT THE JUNCTION. Two earlier versions cut network
    discharge from 2,880 to about 1,000 veh/h whatever rate was configured, because the
    junction they created was itself the bottleneck, in two ways that the produced net
    shows directly. The connections fanned each of 218's three lanes into each of the
    exit road's, so the nine movements crossed and yielded to one another: junction
    218-end carried nine internal lanes and a foe matrix in which movement 2 conflicts
    with six others. And the exit road ran due east while 218 arrives heading 40 degrees
    north of east, so netconvert read every connection as a turn and capped the internal
    lanes at 7.6 to 11.9 m/s against 16.67 m/s on both sides.

    The exit road therefore takes 218's own lane count and its own heading, and lane i
    connects only to lane i. That leaves no crossing movements and no turn, so the only
    thing restricting outflow is the signal, and the rate is a number we choose.

    Returns the discharge the meter allows, in veh/h.
    """
    import sumolib

    loaded = sumolib.net.readNet(str(net))
    link = loaded.getEdge("218")
    source_lanes = link.getLaneNumber()
    lanes = lanes or source_lanes
    end = link.getToNode()
    x, y = end.getCoord()
    # Extend along the link's own final heading. Placing the nodes on a compass
    # direction instead is what made netconvert treat the exit as a turn.
    (px, py), (qx, qy) = link.getShape()[-2:]
    span = math.hypot(qx - px, qy - py)
    ux, uy = (qx - px) / span, (qy - py) / span

    directory = net.parent
    signalled = green_fraction > 0.0
    (directory / "exit.nod.xml").write_text(
        f'<nodes><node id="exit_meter" x="{x + 300.0 * ux:.2f}" '
        f'y="{y + 300.0 * uy:.2f}"'
        f'{" type=\"traffic_light\"" if signalled else ""}/>'
        f'<node id="exit_sink" x="{x + 600.0 * ux:.2f}" '
        f'y="{y + 600.0 * uy:.2f}"/></nodes>')
    (directory / "exit.edg.xml").write_text(
        f'<edges><edge id="exit_road" from="{end.getID()}" to="exit_meter" '
        f'numLanes="{lanes}" speed="{speed_mps:.3f}"/>'
        f'<edge id="exit_tail" from="exit_meter" to="exit_sink" '
        f'numLanes="{lanes}" speed="{speed_mps:.3f}"/></edges>')
    # Merging an edge into an existing SUMO net does not generate the connections into
    # it, so a route through the new edge breaks unless they are given explicitly.
    # Lane i runs straight into lane i where the widths match. Where the exit road is
    # NARROWER the surplus lanes merge into the outermost one, which is a lane drop and
    # a real merge: that turbulence is where a capacity drop comes from, and link 218
    # ending into free outflow has none. Earlier versions fanned every lane into every
    # lane, which made the movements cross and throttled the junction itself.
    connections = "".join(
        f'<connection from="218" to="exit_road" fromLane="{i}" '
        f'toLane="{min(i, lanes - 1)}"/>' for i in range(source_lanes)
    ) + "".join(
        f'<connection from="exit_road" to="exit_tail" fromLane="{i}" toLane="{i}"/>'
        for i in range(lanes))
    (directory / "exit.con.xml").write_text(f"<connections>{connections}</connections>")
    # The meter's program, written out rather than derived, so the green share is the
    # number chosen and not whatever netconvert infers.
    yellow = 3.0
    green = max(5.0, round(green_fraction * cycle_s - yellow)) if signalled else cycle_s
    red = max(5.0, cycle_s - green - yellow) if signalled else 0.0
    (directory / "exit.tll.xml").write_text(
        "<tlLogics></tlLogics>" if not signalled else
        f'<tlLogics><tlLogic id="exit_meter" type="static" programID="0" offset="0">'
        f'<phase duration="{green:.0f}" state="{"G" * lanes}"/>'
        f'<phase duration="{yellow:.0f}" state="{"y" * lanes}"/>'
        f'<phase duration="{red:.0f}" state="{"r" * lanes}"/>'
        f'</tlLogic></tlLogics>')
    binary = REPO_ROOT / ".venv" / "bin" / "netconvert"
    result = subprocess.run(
        [str(binary if binary.exists() else "netconvert"),
         "--sumo-net-file", str(net),
         "--node-files", str(directory / "exit.nod.xml"),
         "--edge-files", str(directory / "exit.edg.xml"),
         "--connection-files", str(directory / "exit.con.xml"),
         "--tllogic-files", str(directory / "exit.tll.xml"),
         "-o", str(net)],
        capture_output=True, text=True)
    if result.returncode != 0:
        sys.stderr.write(result.stderr)
        raise SystemExit("netconvert failed adding the exit constraint")
    drop_build_time(net)
    # An upper bound only: the W99 following distance at free-flow speed, times the
    # green share. Real discharge is well under it, because a queue restarting from
    # rest does not reach free-flow headways within a green. At 0.85 green the bound is
    # 3,206 veh/h and `measure_fd_exit.py` reads about 1,900.
    per_lane = speed_mps / (speed_mps * 2.5 + 4.5) * 3600
    return per_lane * lanes * (green / cycle_s)


def run_netconvert(inpx: Path, out: Path) -> None:
    binary = REPO_ROOT / ".venv" / "bin" / "netconvert"
    command = [
        str(binary if binary.exists() else "netconvert"),
        "--vissim-file", str(inpx),
        # Without this the imported z-offsets produce edge grades up to 923%, which
        # SUMO applies to acceleration.
        "--flatten",
        "--speed.factor", str(SPEED_FACTOR),
        "-o", str(out),
    ]
    result = subprocess.run(command, capture_output=True, text=True)
    if result.returncode != 0:
        sys.stderr.write(result.stderr)
        raise SystemExit(f"netconvert failed with code {result.returncode}")
    refused = re.findall(r"Will not build edge '(\d+)'", result.stderr)
    if refused:
        print(f"  netconvert refused {len(refused)} edges: {sorted(refused, key=int)}")


def edge_ids(net_file: Path) -> set[str]:
    root = ET.parse(net_file).getroot()
    return {
        edge.get("id")
        for edge in root.findall("edge")
        if edge.get("function") != "internal"
    }


def expand(link_no: str, present: set[str]) -> list[str]:
    """A Vissim link id as the SUMO edges it became, in order.

    Returns the empty list for a link netconvert did not build, so a caller that
    drops it does so knowingly rather than by producing a route with a hole in it.
    """
    if link_no in present:
        return [link_no]
    parts = sorted(
        (e for e in present if re.fullmatch(rf"{re.escape(link_no)}\[\d+\]", e)),
        key=lambda e: int(e.split("[")[1].rstrip("]")),
    )
    return parts


def outgoing(net_file: Path) -> dict[str, set[str]]:
    """Edge to the edges reachable from it in one step, via connections."""
    root = ET.parse(net_file).getroot()
    links: dict[str, set[str]] = {}
    for connection in root.findall("connection"):
        source, target = connection.get("from"), connection.get("to")
        if source and target and not source.startswith(":"):
            links.setdefault(source, set()).add(target)
    return links


def demand(inpx_root: ET.Element) -> dict[str, list[tuple[float, float, float]]]:
    """Entry link to its `(start_s, end_s, veh/h)` intervals.

    The demand is NOT constant and reading only its first interval more than doubles
    it: every entry runs at its stated volume for the first 1,200 s and at zero
    afterwards, so the episode is a twenty-minute surge followed by a drain. Holding
    the opening volume for the whole 2,500 s offers 12,500 vehicles where the scenario
    offers 6,000.
    """
    schedule: dict[str, list[tuple[float, float, float]]] = {}
    for vehicle_input in inpx_root.find("vehicleInputs").findall("vehicleInput"):
        points = sorted(
            (float(entry.get("timeInt").split()[1]) / 1000.0, float(entry.get("volume")))
            for entry in vehicle_input.find("timeIntVehVols").findall("timeIntervalVehVolume")
        )
        if not any(volume > 0.0 for _, volume in points):
            continue
        intervals = []
        for index, (start, volume) in enumerate(points):
            end = points[index + 1][0] if index + 1 < len(points) else float("inf")
            if volume > 0.0:
                intervals.append((start, end, volume))
        schedule[vehicle_input.get("link")] = intervals
    return schedule


def routes(inpx_root: ET.Element, present: set[str], entries: set[str],
           exit_road: bool = False) -> dict[str, list[str]]:
    """Entry link to its route as SUMO edges.

    Every route in this network ends at link 218, so one route per entry describes the
    demand completely and no route choice has to be modelled.
    """
    built: dict[str, list[str]] = {}
    decisions = inpx_root.find("vehicleRoutingDecisionsStatic")
    for decision in decisions.findall("vehicleRoutingDecisionStatic"):
        entry = decision.get("link")
        if entry not in entries or entry in built:
            continue
        static = decision.find("vehRoutSta")
        if static is None:
            continue
        for route in static.findall("vehicleRouteStatic"):
            # THE ROUTE STARTS AT THE ENTRY LINK. A Vissim routing decision sits ON a
            # link at some position along it and its `linkSeq` is the path onward from
            # there, so the sequence alone omits the link the vehicles are generated
            # on. Dropping it inserted traffic directly onto the next edge, which for
            # three of the eight entries is a single lane where the entry link has two
            # or three, throttling insertion and leaving thousands of vehicles queued
            # outside a network that never filled.
            # THE ROUTE ALSO ENDS AT THE DESTINATION LINK. `linkSeq` is the path
            # BETWEEN the decision point and the destination and names neither, so a
            # route built from it alone omits both ends. The destination here is link
            # 218, three lanes where the link feeding it has four -- a lane drop at the
            # exit. Skipping it removed the network's own outflow constraint and let
            # vehicles leave from a four-lane edge into nothing.
            sequence = [entry] + [
                ref.get("key") for ref in route.find("linkSeq").findall("intObjectRef")
            ] + [route.get("destLink")] + (["exit_road", "exit_tail"] if exit_road else [])
            path = [edge for key in sequence for edge in expand(key, present)]
            if path:
                built[entry] = path
                break
    return built


def check_connected(path: list[str], links: dict[str, set[str]]) -> list[tuple[str, str]]:
    return [
        (path[i], path[i + 1])
        for i in range(len(path) - 1)
        if path[i + 1] not in links.get(path[i], set())
    ]


def rush(volumes: dict[str, list[tuple[float, float, float]]],
         duration_s: float) -> dict[str, list[tuple[float, float, float]]]:
    """Reshape every entry's demand into a rush that rises to a peak and falls back.

    A constant rate puts the network at one point on its flow-density curve and leaves
    it there, so tracing the curve needs one run per point. A rush traces it in a single
    run: demand climbs from a quarter of the peak to the peak and back down, and a
    detector on the road passes through free flow, capacity and congestion as the queue
    from the downstream restriction grows over it and then clears.

    Both halves are kept so they can be compared. If the loading and unloading legs do
    not lie on the same branches, what is being measured is a transient rather than a
    property of the road.

    The opening volume of each entry is its peak, so `--demand-scale` sets the height of
    the rush and the mix across the eight entries is the scenario's own.
    """
    steps = 12
    half = duration_s / 2.0
    shape = [(half * index / (steps - 1), 0.25 + 0.75 * index / (steps - 1))
             for index in range(steps)]
    shape += [(half + half * index / (steps - 1), 1.0 - 0.75 * index / (steps - 1))
              for index in range(1, steps)]
    reshaped = {}
    for entry, intervals in volumes.items():
        peak = intervals[0][2]
        reshaped[entry] = [
            (start,
             shape[index + 1][0] if index + 1 < len(shape) else duration_s,
             peak * share)
            for index, (start, share) in enumerate(shape)
        ]
    return reshaped


def vtype_lines(model: str = "eidm_reaction",
                junction_block_s: float | None = None) -> list[str]:
    """Vehicle types from a named human-model config.

    Every key under the config's `sumo` block other than the model name and the
    standstill gap is written straight through as a vType attribute, so a config can
    carry W99's cc1..cc9 or EIDM's tau and actionStepLength without this function
    knowing which.

    The default is `eidm_reaction` rather than the paper's `w99_calibrated`. Under W99
    a bottleneck's discharge does not fall once a queue stands behind it -- it rises --
    so served flow is a constant and there is no capacity drop for a density-holding
    controller to recover. That config's header carries the measurements.
    """
    import yaml

    config = yaml.safe_load(
        (REPO_ROOT / "configs" / "human_models" / f"{model}.yaml").read_text())
    sumo = config["sumo"]
    attributes = " ".join(
        f'{name}="{value}"' for name, value in sumo.items()
        if name not in ("car_following_model", "min_gap_m")
    )
    common = (f'carFollowModel="{sumo["car_following_model"]}" '
              f'minGap="{sumo["min_gap_m"]}" {attributes} maxSpeed="16.67"')
    if junction_block_s is not None:
        # JUNCTION BLOCKING, AND IT IS A MODELLING CHOICE OF OURS, not the paper's.
        # SUMO keeps a vehicle out of a junction it cannot clear, which prevents
        # deadlock and also prevents the throughput loss that blocking causes in a
        # real network: measured with no control, Mainz served a constant 2,853 to
        # 2,894 veh/h while interior links reached 125 veh/km/lane at 0.8 km/h, so
        # gridlock cost it nothing. `jmIgnoreKeepClearTime` is the accumulated waiting
        # time after which a vehicle enters anyway; SUMO's default of -1 means never.
        # Vissim's conflict areas model the same behaviour, which is the ground for
        # choosing it, but the value here is ours and is not transcribed from anything.
        common += f' jmIgnoreKeepClearTime="{junction_block_s:g}"'
    return [
        f'  <vType id="human" {common}/>',
        f'  <vType id="av" {common} color="1,0,0"/>',
    ]


def write_routes(out_path: Path, built: dict[str, list[str]], volumes: dict[str, float],
                 duration_s: float, av_fraction: float, seed: int,
                 junction_block_s: float | None = None,
                 human_model: str = "eidm_reaction") -> int:
    """One explicit departure per vehicle, evenly spaced, sorted by time.

    Explicit vehicles rather than `<flow>` so a vehicle's id encodes whether it is an
    AV: SRC selects its controlled subset by vehicle number, and reproducing that here
    keeps the penetration deterministic and inspectable instead of resting on a draw.

    Three files are written from the one schedule, so the two admission policies are
    the same demand rather than two demands that happen to match:

    * `mainz.rou.xml`, routes and every vehicle, which SUMO inserts on its own terms.
    * `mainz_routes.rou.xml`, the same routes and vehicle types with no vehicles, for
      runs where `MainzEnv` grants entry itself.
    * `mainz_schedule.json`, the vehicles that file omits, with the entry link each one
      is waiting at so the gate can be applied per entry.
    """
    header = ["<routes>"] + vtype_lines(human_model, junction_block_s)
    for entry, edges in sorted(built.items(), key=lambda kv: int(kv[0])):
        header.append(f'  <route id="r{entry}" edges="{" ".join(edges)}"/>')
    departures: list[tuple[float, str, str]] = []
    for entry, intervals in sorted(volumes.items(), key=lambda kv: int(kv[0])):
        if entry not in built:
            continue
        for start, end, rate in intervals:
            headway = 3600.0 / rate
            time = start + headway / 2.0
            limit = min(end, duration_s)
            while time < limit:
                departures.append((time, entry, f"v{entry}_{len(departures)}"))
                time += headway
    departures.sort()
    schedule = []
    lines = list(header)
    for index, (time, entry, vehicle_id) in enumerate(departures):
        kind = "av" if (index % round(1.0 / av_fraction) == 0) else "human"
        lines.append(
            f'  <vehicle id="{vehicle_id}" type="{kind}" route="r{entry}" '
            f'depart="{time:.2f}" departSpeed="max" departLane="best"/>'
        )
        schedule.append({"id": vehicle_id, "route": f"r{entry}", "type": kind,
                         "depart": round(time, 2), "entry": entry})
    lines.append("</routes>")
    out_path.write_text("\n".join(lines) + "\n")
    out_path.with_name("mainz_routes.rou.xml").write_text(
        "\n".join(header + ["</routes>"]) + "\n")
    out_path.with_name("mainz_schedule.json").write_text(json.dumps(schedule))
    return len(departures)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--duration-s", type=float, default=2500.0,
                        help="episode length; departures are never written past it, so "
                             "raising --demand-duration-s alone does nothing")
    # The published RL.py controls every second vehicle, but that script produces the
    # paper's ABLATION row, not its main table. The main table is at full penetration,
    # so matching the headline result means 1.0 and reading the code would have given
    # the wrong answer.
    parser.add_argument("--av-fraction", type=float, default=1.0,
                        help="1.0 for the paper's main table; its ablation uses 0.5")
    parser.add_argument("--seed", type=int, default=1)
    parser.add_argument("--no-exit-meter", action="store_true",
                        help="leave the exit unconstrained. Link 218 alone caps "
                             "outflow at 3,899 veh/h, above the 2,880 the network "
                             "delivers, so without the meter the exit never binds and "
                             "vehicles leave as fast as they arrive")
    parser.add_argument("--exit-lanes", type=int, default=0,
                        help="lanes on the road the network exits into; 0 matches link "
                             "218's three. Fewer is a lane drop, which is a merge, and "
                             "a merge is where a capacity drop comes from -- 218 ends "
                             "into free outflow and has none")
    parser.add_argument("--exit-speed-mps", type=float, default=16.67)
    parser.add_argument("--exit-green-fraction", type=float, default=0.0,
                        help="share of the cycle the exit meter is green. Measured "
                             "discharge is about 1,900 veh/h at 0.85 and 1,440 at "
                             "0.62, against the 2,880 veh/h the network delivers with "
                             "no meter, so the exit binds over this whole range")
    parser.add_argument("--exit-cycle-s", type=float, default=60.0)
    parser.add_argument("--demand-duration-s", type=float, default=None,
                        help="hold the opening volume for this long instead of using "
                             "the .inpx intervals; the published scenario surges for "
                             "1,200 s and then stops, which leaves the rest of the "
                             "episode draining rather than at an operating point")
    parser.add_argument("--human-model", default="eidm_reaction",
                        help="a config under configs/human_models. The paper's "
                             "w99_calibrated has no capacity drop on SUMO, so it cannot "
                             "support a throughput claim; see that config's header")
    parser.add_argument("--junction-block-after-s", type=float, default=None,
                        help="seconds of accumulated waiting after which a vehicle "
                             "enters a junction it cannot clear, blocking it. SUMO "
                             "never does this by default, which is why gridlock costs "
                             "this network no throughput. Ours, not the paper's")
    parser.add_argument("--demand-rush-s", type=float, default=None,
                        help="reshape demand into a rush of this length that climbs "
                             "from a quarter of the opening volume to it and back, so "
                             "one run traces the whole flow-density curve instead of "
                             "sitting at one point on it")
    parser.add_argument("--demand-scale", type=float, default=1.0,
                        help="multiply every entry volume, to place the network at a "
                             "chosen point on its flow-density curve")
    args = parser.parse_args()

    inpx = DATA / "Mainz20base.inpx"
    net_file = DATA / "mainz.net.xml"
    if not inpx.exists():
        raise SystemExit(f"missing {inpx}; see data/mainz in .gitignore for its origin")

    print("building the network")
    run_netconvert(inpx, net_file)
    if not args.no_exit_meter:
        allowed = add_exit_constraint(net_file, args.exit_speed_mps,
                                      args.exit_green_fraction, args.exit_cycle_s,
                                      args.exit_lanes)
        shape = (f"{args.exit_lanes} lanes" if args.exit_lanes else "218's own width")
        meter = (f", metered at {args.exit_green_fraction:.2f} green"
                 if args.exit_green_fraction > 0.0 else ", unsignalled")
        print(f"  exit: {shape}{meter}, at most {allowed:.0f} veh/h")
    present = edge_ids(net_file)
    links = outgoing(net_file)
    print(f"  {len(present)} named edges")

    root = ET.parse(inpx).getroot()
    volumes = demand(root)

    built = routes(root, present, set(volumes), not args.no_exit_meter)
    for entry, path in sorted(built.items(), key=lambda kv: int(kv[0])):
        breaks = check_connected(path, links)
        status = "ok" if not breaks else f"BREAKS {breaks[:2]}"
        print(f"  route from {entry}: {len(path)} edges, {status}")
    if len(built) != len(volumes):
        raise SystemExit(f"only {len(built)} of {len(volumes)} entries have a route")

    if args.demand_duration_s is not None:
        volumes = {entry: [(0.0, args.demand_duration_s, intervals[0][2])]
                   for entry, intervals in volumes.items()}
    if args.demand_scale != 1.0:
        volumes = {entry: [(a, b, v * args.demand_scale) for a, b, v in intervals]
                   for entry, intervals in volumes.items()}
    if args.demand_rush_s is not None:
        volumes = rush(volumes, args.demand_rush_s)
        peak = sum(max(v for _, _, v in intervals) for intervals in volumes.values())
        print(f"  demand: {len(volumes)} entries, a rush over "
              f"{args.demand_rush_s:g} s peaking at {peak:g} veh/h")
    else:
        opening = sum(intervals[0][2] for intervals in volumes.values())
        last_end = min(max(i[1] for intervals in volumes.values() for i in intervals),
                       args.duration_s)
        print(f"  demand: {len(volumes)} entries, {opening:g} veh/h until "
              f"{last_end:g} s, then zero")
    count = write_routes(DATA / "mainz.rou.xml", built, volumes,
                         args.duration_s, args.av_fraction, args.seed,
                         args.junction_block_after_s, args.human_model)
    print(f"  {count} vehicle departures over {args.duration_s:g} s")

    groups = eval((DATA / "rl_links_mainz.txt").read_text())
    segments, dropped = [], []
    for group in groups:
        members: list[str] = []
        for link_no in group:
            parts = expand(str(link_no), present)
            if parts:
                members.extend(parts)
            else:
                dropped.append(str(link_no))
        segments.append(members)
    (DATA / "mainz_segments.json").write_text(json.dumps(segments, indent=1))
    covered = sum(len(s) for s in segments)
    print(f"  {len(segments)} super-segments over {covered} edges; "
          f"dropped {sorted(set(dropped), key=int)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
